name: gherkin_plus
version: 0.1.0-dev.1
description: A modern, explicit Gherkin parser and runner for Dart applications.
repository: https://github.com/jonsamwell/dart_gherkin

dependencies:
  path: ^1.9.0
  collection: ^1.19.0
  uuid: ^4.5.1
  matcher: ^0.12.20
  cucumber_gherkin: ^42.0.1
  cucumber_messages: ^34.0.2

dev_dependencies:
  lint: ^2.3.0
  test: ^1.32.0
  glob: ^2.1.3

environment:
  sdk: ">=3.8.0 <4.0.0"
